### PR TITLE
Adding custom parameters in the search

### PR DESCRIPTION
**Pull request by cakama3a**
Pressing the Enter-button, adds the input parameter.

### CODE REVIEW

**Comment by HemantNegi** [comment]
Please can u explain the use case of this.

**Comment by cakama3a** [comment]
https://youtu.be/G4tHVYhWSew

**Comment by HemantNegi** [comment]
Not merging now!
Let us see if people actually need this.

**Comment by Aphyxia** [comment]
Client requested this, so might be worth considering merging.

**Comment by Zenoo** [comment]
#275 managed to achieve the same result without needing much added code.

**Pull request closed without merging**
