### PR TITLE
select and unselect all the options

### PR DESCRIPTION
**Pull request by celiaks**
the functions SelectAll/unSelectAll let us select/unselect all the options of a specific select tag

### CODE REVIEW

**Comment by HemantNegi** [comment]
Done Buddy
Thanks for contribution.

Cheers!!

**Comment by celiaks** [comment]
no problem :)

**Comment by mcaulayj** [comment]
Hi there, thanks for this script and also thanks for the contribution.

Noob question, how can I add an option in the drop down to allow select all?

Regards, John.

**Comment by HemantNegi** [comment]
Unfortunately its not there as of now, Will consider in next release soon.

Thanks

**Comment by celiaks** [comment]
i will pull request for it in juqery.sumoselect.js there is some line to write in differents places in the file, so it will be too complicated to answer you here.

**Comment by celiaks** [comment]
receaved ?

**Comment by mcaulayj** [comment]
Thank you this is exactly what I wanted!!

**Pull request merged**
