### PR TITLE
triggering 'toggled' event whenever the sumoSelect is opened or closed

### PR DESCRIPTION
**Pull request by trexpert**
Added 'toggled' events with status at second parameter

### CODE REVIEW

**Comment by HemantNegi** [comment]
Whats is the use case of this.

**Comment by trexpert** [comment]
sometimes it's required to know when the select is opened and closed. darker the site on open...  sort the entries on close...

**Comment by cprater** [comment]
I was about to submit a PR of something similar...It would be a bit more helpful if the events were named more specifically. Like `opening`, `opened`, `closing` and `closed`

**Comment by trexpert** [comment]
I think it's better to get just one event when popup is toggled. The first parameter can represent the status. It's purely a matter of taste... i prefer handling a single event of the same type. Open and close is the same type of event with just another direction.

In fact this SumoSelect need to throw any kind of event. i dont want to start a dissertation at this point.

**Comment by cprater** [comment]
Most 3rd party dropdown plugins of this nature have an event system that includes at least `open` and `closed` events. Those are pretty standard because they are clear, specific, and easy to understand the state of the dropdown without the need of handling additional parameters.

https://select2.github.io/examples.html#programmatic-control
https://github.com/selectize/selectize.js/blob/master/docs/events.md
http://gregfranko.com/jquery.selectBoxIt.js/#EventsAPI

**Comment by trexpert** [comment]
so start a new fork with modified events

**Pull request closed without merging**
