### PR TITLE
Adding filtering capacity

### PR DESCRIPTION
**Pull request by te-deum**
Here is a filtering function. *(You can now activat filtering independantly from selectAll)*

You have to set the option _**filter**_ to _**true**_.
You can change the place holder text with the _**filterText**_ option.

You can test it with *select_responsive_filter.html* file.
Hope you will find this usefull.

### CODE REVIEW

**Comment by jarnanchen** [comment]
Great Work

**Comment by mediatack** [comment]
Works fine with multiselect, but can you make the searchbox also available for singelselects? It would be a great improvement for long lists.

**Comment by te-deum** [comment]
I have changed the way it work to handle every modes.
You can now activat filtering independantly from selectAll.

Filtering is no more activate by default. You have to set the option filter to true.
You can change the place holder text with hte filterText option.

You can test it with select_responsive_filter.html file.

**Comment by HemantNegi** [comment]
Thanks @te-deum 
seems nice and functional.
Let me test and i will merge.

**Comment by camway** [comment]
I don't want to annoy, but has any progress been made toward getting this merged?  We had a request to implement this functionality and I'm trying to avoid hacking it together.  Not really any rush, but if the next release was coming up I wasn't going to try to force this into our project.

Thanks in advance!

**Comment by HemantNegi** [comment]
Hi every one here,

I have pushed a working draft of search in master branch.
can u please test it on your end.
Thanks

**Pull request merged**
