### PR TITLE
Display placeholder before selected items

### PR DESCRIPTION
**Pull request by dmytrofeshchenko**
Hello. I've needed to display placeholder before selected items at my filter with several fields. I think that it will be useful for some one else. 
Thanks.

### CODE REVIEW

**Comment by HemantNegi** [comment]
Hi,
Please can u explain the use case.

**Comment by dmytrofeshchenko** [comment]
Re: [jquery.sumoselect] Display placeholder before selected items (#91)



Hi.

I've made the filters at mobile version of one ukrainian e-commerce website http://m.aks.ua/catalog/mobilnye-telefony/

So we have no labels for fields.. only placeholders. But when you select few fields (they can be different for different groups of goods) you can forget, what does this field / filter mean.
So i decided to leave placeholder visible after selecting (http://prntscr.com/a6v2fy )  to make filter more convenient 

thanks for asking..

Monday, February 22, 2016, 7:18:15 PM, you wrote:





Hi,
Please can u explain the use case.
—
Reply to this email directly or view it on GitHub.




-----------------------------------------------
С уважением,
Дмитрий Фещенко
Менеджер проектов
DF-Studio - Лучшие решения для Вашего бизнеса!

**Comment by HemantNegi** [comment]
Something similar can be achieved by `captionFormat` . 
I don't see a much wider use of this. 
So can not merge now.

**Comment by dmytrofeshchenko** [comment]
Re: [jquery.sumoselect] Display placeholder before selected items (#91)



Hello Hemant,

Tuesday, February 23, 2016, 3:48:12 PM, you wrote:





Something similar can be achieved by captionFormat . 
I don't see a much wider use of this. 
So can not merge now.
—
Reply to this email directly or view it on GitHub.



OK. not a problem. Thanks

-- 
Best regards,
 Backend                            mailto:backend@df-studio.net

**Comment by HemantNegi** [comment]
Ok so i have added a setting named `prefix` as it does not costs much. which can contain some html also.

**Comment by dmytrofeshchenko** [comment]
Re: [jquery.sumoselect] Display placeholder before selected items (#91)



Hello Hemant,

great! thanks

Tuesday, February 23, 2016, 4:15:38 PM, you wrote:





Ok so i have added a setting named prefix as it does not costs much. which can contain some html also. 
—
Reply to this email directly or view it on GitHub.




-----------------------------------------------
С уважением,
Дмитрий Фещенко
Менеджер проектов
DF-Studio - Лучшие решения для Вашего бизнеса!

**Pull request closed without merging**
