### PR TITLE
 Add custom match function for search

### PR DESCRIPTION
**Pull request by MaxQNEI**

### CODE REVIEW

**Comment by HemantNegi** [comment]
Is this really needed?
What use-case will it serve.

**Comment by MaxQNEI** [comment]
Searching by cities & regions without search text in brackets...
For example, we need search "Kiev", but found:

Boguslav (**Kiev** region)
Borovaya (**Kiev** region)
**Kiev** << **NEED ONLY THIS**
Kozin (**Kiev** region)
Novoselki (**Kiev**-Svyatoshinsky district)
Rakitnoe (**Kiev** region, Rakitnyansky district)
Svyatopetrovsk (**Kiev**-Holy district)
Trypillya (**Kiev** region)

In other situations, searchFn can use not only as search, but and for sort results.

searchFn uses on amrita.ua for search delivery dep. in basket.

**Comment by HemantNegi** [comment]
Got it.
Please can you update the docs also.

**Comment by MaxQNEI** [comment]
Hi HemantNegi, README.md updated.

**Pull request merged**
